:sectnums:
:toc: macro
ifdef::env-github[]
:!toc-title:
endif::[]

= xcikit

Collection of C++ libraries for drawing 2D graphics, rendering text and more.

toc::[]

== About

Xcikit contains basic elements needed for creating 2D graphical applications.
The focus is on text rendering and closely related UI rendering. Additional
features are a custom scripting language and data serialization.

With xcikit you can:

* render a few paragraphs of text,
* style some parts of the text differently (colored highlights),
* respond to mouse hover, click on the highlighted parts (spans),
* create a basic UI with buttons, checkboxes, combo-boxes,
* support scripting, provide sandboxed API for user scripts.

This should be enough for a program to render:

* 2D sprites,
* menu,
* settings screen,
* dialogs.

The library uses GLFW and Vulkan for graphics.

== Features

Note that xcikit is still under development and mostly experimental.
There is no stable API. There are no releases. The features below are partially planned,
but already implemented to some degree.

The planned features:

* GPU oriented 2D graphics
* advanced text rendering
* UI widgets (not meant to replace Qt, but should be good enough for indie games)
* data file management (VFS)
* custom scripting language (it wasn't planned originally, but it's fun to design and implement)
* support library (logging, eventloop etc.)

The features are divided into a set of libraries:

* `xci-widgets`
* `xci-text`
* `xci-graphics`
* `xci-script`
* `xci-data`
* `xci-core`

The separation of the code into libraries helps to create layers
and avoid bi-directional dependencies. Basically, each library can depend only
on the libraries listed below it. (TODO: draw a dependency graph)

The top-level `xci-widgets` provides UI components with event processing.
It uses text layout engine `xci-text`, which can also be used separately.

All rendering goes through GLFW and Vulkan based `xci-graphics` library.
Graphics lib can be used separately when neither UI nor text rendering
is needed.

Optional `xci-data` library provides custom text and binary format
for serialization / deserialization of hierarchical data structures.
Think of Json and Google Protobuf, but without the complexity and bloat.

All of the above use `xci-core`, which contains miscellaneous utilities,
This can also be used separately.

There is also header-only `compat` library, which is used to hide
differences between compilers and OS's. It does not implement any
abstraction layer, but just provides what is available elsewhere.

Technologies:

* C++20 as main programming language
* CMake as build system
* Conan as dependency manager

Tested compilers:

* GCC 10 (Debian 11 Bullseye)
* Clang 10 (macOS via Homebrew)

Any Unix-like OS with C++20 compliant compiler should work. There is no direct Windows support,
but it's possible that the project will compile with some layer of Unix compatibility, e.g. WSL.
Some of the libraries already compile natively, see <<windows,Porting to Windows>>.

== Libraries

=== xci::widgets

Basic UI elements.

=== xci::text

Text rendering and text layout.

=== xci::graphics

The basic building blocks for rendering of text and UI elements.

=== xci::script

Experimental scripting language with bytecode interpreter and C transpiler.

Docs:

* link:docs/script/syntax.adoc[Fire Script Syntax Reference]
+
It's not fully implemented, so it's more precisely a design document at this time. It will become actual reference in version 1.0.

* link:docs/script/machine.adoc[Fire Script Virtual Machine]

The C transpiler is not yet available.

=== xci::data

Serialization and deserialization of structured data.

=== xci::core

Core utilities. These have little or no dependencies. Mostly just stdlib + OS API.

* `Buffer` (`types.h`) - Owned blob of data, with deleter.
* `FpsCounter` - Tracks delays between frames and computes frame rate.
* `Logger` (`log.h`) - Logging functions.
* `SharedLibrary` - Thin wrapper around dlopen. For plugins.
* `TermCtl` - Colored output for ANSI terminals.
* `Vfs` - Unified reading of regular files and archives. Mount the archive to virtual path
 and read contained files in same fashion as regular files.
* `event.h` - System event loop (abstraction of kqueue / epoll).
* `dispatch.h` - Watch files and notify on changes. Useful for auto-reloading of resource files.
* `file.h` - Read whole files. Path utilities (dirname, basename, …).
* `format.h` - Formatted strings. Similar to Python's `format()`.
* `geometry.h` - 2D vector, rectangle. Linear algebra.
* `rtti.h` - C++ demangled type names.
* `string.h` - String manipulation. Unicode utilities.
* `sys.h` - A replacement for `std::this_thread::get_id()`, providing the canonical TID.

=== xci::compat

Fills gaps between different systems and compilers.

* `bit.h` - custom `bit_read`, similar to C++20 `bit_cast`
* `dl.h` - `dlopen` etc. for Windows
* `endian.h` - Linux-like macros provided for MacOS
* `macros.h` - `FALLTHROUGH`, `UNREACHABLE`, `UNUSED`
* `unistd.h` - Minimal Unix compatibility header for Windows

== Tools

Included are some tools build on top of the libraries.
Check them on separate pages:

* link:tools/README.md[XCI Tools]
** link:tools/find_file/README.md[Find File (ff)] - `find` alternative

== How to build

Build system (required):

- CMake (eg. `apt-get install cmake`)

Package manager (optional):

- Conan (eg. `pip3 install conan`)

Dependencies:

- PEGTL (xci-core)
- libzip (xci-core/XCI_WITH_ZIP)
- FreeType (xci-text)
- GLFW, Vulkan (xci-graphics)
- https://github.com/google/shaderc[glslc] or
https://github.com/KhronosGroup/glslang[glslangValidator] (xci-graphics)
- https://github.com/catchorg/Catch2[Catch2] for tests
- https://github.com/google/benchmark[Google Benchmark]

Some of the dependencies are installed by Conan if not found in the system
(e.g. PEGTL, range-v3, GLFW). Others must be provided by the system (Vulkan).

Installing the dependencies:

- Debian: `apt-get install libzip-dev`
- macOS (Homebrew): `brew install libzip`
- macOS (MacPorts): `port install vulkan-* MoltenVK glfw-devel freetype hyperscan cmake ninja`

=== Using build script

This should be run once to download missing files etc.:

[source,bash]
----
./bootstrap.sh
----

The complete build process is handled by build script:

[source,bash]
----
./build.sh
----

When finished, you'll find the temporary build files in `build/`
and installation artifacts in `artifacts/`.

Both scripts are incremental, so it's safe to run them repeatably.
They do only the required work and re-use what was done previously.

=== Manual build with CMake

Detailed build steps (these are examples, adjust parameters as needed):

[source,bash]
----
# Configure Conan remotes, download additional assets
./bootstrap.sh

# Prepare build directory
mkdir build && cd build

# Install dependencies using Conan.
conan install .. --build missing -s compiler=clang

# Configure
cmake .. -G Ninja -DCMAKE_INSTALL_PREFIX=~/sdk/xcikit

# Adjust CMake configuration
ccmake ..

# Build
cmake --build .

# Run unit tests
cmake --build . --target 'test'

# Install (default prefix is /usr/local)
cmake --build . --target 'install'
----

=== Building on macOS older than Catalina (10.15)

Using [MacPorts](https://www.macports.org/), install Clang 11 and libc++:

----
port install clang-11 macports-libcxx
----

Then create a `clang11-toolchain.cmake` file with content like this:

[source,cmake]
----
set(CMAKE_CXX_COMPILER /opt/local/bin/clang++-mp-11)
add_compile_options(-nostdinc++ -I/opt/local/include/libcxx/v1 -D_LIBCPP_DISABLE_AVAILABILITY)
add_link_options(-L/opt/local/lib/libcxx)
----

Run the build with this toolchain:

[source,bash]
----
./build.sh --toolchain clang11-toolchain.cmake
----

[#windows]
=== Porting to Windows

The project is not yet fully ported to Windows.But the essential parts should
already work:

* dependencies via Conan
* build scripts (using git-bash)
* CMake configuration and build
* core and script libraries + demos

How to build:

1. Enable https://docs.microsoft.com/en-us/windows/uwp/get-started/enable-your-device-for-development[Developer mode]
(required for ability to create symlinks)

2. Install build tools via their Windows installers: Git, CMake, Conan
(`git`, `cmake` and `conan` commands should now work in `cmd.exe`)

3. Open _Git Bash_ and run `./bootstrap.sh`

4. Still in _Git Bash_, run `./build.sh -D XCI_GRAPHICS=0`

5. There might be errors.These are why the title says "Porting", not "How to build"…

[#emscripten]
=== Porting to Emscripten

The non-graphical components should build with Emscripten.

Install and link https://emscripten.org/[Emscripten] so that this command works: `emcc -v`

Create a https://docs.conan.io/en/latest/integrations/cross_platform/emscripten.html[Conan profile for Emscripten], for example:

[source,ini]
----
[settings]
os=Emscripten
arch=wasm
compiler=clang
compiler.version=11
compiler.libcxx=libc++
build_type=Release
[options]
[build_requires]
[env]
# Find actual path Emscripten installation (or check CMake command line, when called with emcmake)
CONAN_CMAKE_TOOLCHAIN_FILE=.../cmake/Modules/Platform/Emscripten.cmake
----

See a working example of such profile in the link:docker/emscripten/conan/profile[docker/emscripten] directory.

Set this profile to be used by default:

[source,bash]
----
export CONAN_DEFAULT_PROFILE_PATH=emscripten
----

Run the build (only 'core' and 'script' components work at this time):

[source,bash]
----
./build.sh --debug --emscripten core script
----

== How to use in a client program

=== Linking with a client using only CMake

Build and install XCI libraries (see "How to build" above),
then use installed `xcikitConfig.cmake` in your project's
`CMakeLists.txt`:

[source,cmake]
----
cmake_minimum_required(VERSION 3.15)
project(example CXX)

set(CMAKE_CXX_STANDARD 17)
set(CMAKE_POSITION_INDEPENDENT_CODE ON)
set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -Wall -Wextra -Wno-unused-parameter")

find_package(xcikit REQUIRED)

add_executable(example src/main.cpp)
target_link_libraries(example xci-widgets)
----

In the case xcikit was installed into non-standard location,
for example `~/sdk/xcikit`, you need to setup `CMAKE_PREFIX_PATH` appropriately:

[source,bash]
----
cmake -DCMAKE_PREFIX_PATH="~/sdk/xcikit" ..
----

=== Linking with a client using CMake and Conan

Add xcikit as dependency to `conanfile.txt`:

----
[requires]
xcikit/0.1@rbrich/stable

[generators]
cmake_paths
----

Then include generated `conan_paths.cmake` from project's `CMakeLists.txt`:

[source,cmake]
----
if (EXISTS ${CMAKE_BINARY_DIR}/conan_paths.cmake)
    include(${CMAKE_BINARY_DIR}/conan_paths.cmake)
endif()
----

Now find `xcikit` in usual way:

[source,cmake]
----
find_package(xcikit REQUIRED)
----

Optionally, include XCI goodies:

[source,cmake]
----
include(XciBuildOptions)
----

Link with the libraries:

[source,cmake]
----
target_link_libraries(example xcikit::xci-text xcikit::xci-graphics)
----
