# CircleCI + Docker howto: https://circleci.com/docs/2.0/custom-images/

version: 2
jobs:
  build:
    docker:
      - image: rbrich/xcikit:debian-11

    steps:
      - checkout

      - run:
          name: Bootstrap
          command: ./bootstrap.sh -y

      - run:
          name: Deps
          command: ./build.sh deps

      - run:
          name: Configure
          command: ./build.sh config

      - run:
          name: Build
          command: ./build.sh build -j 2

      - run:
          name: Run tests
          command: ./build.sh test

      - run:
          name: Install
          command: ./build.sh install

      - run:
          name: Package
          command: ./build.sh package

      - store_artifacts:
          path: artifacts
