# Find Panda3D
#
# optionally set PANDA3D_ROOT to custom root

find_path(PANDA3D_INCLUDE_DIR pandaFramework.h
    PATH_SUFFIXES panda3d
    PATHS ${PANDA3D_ROOT})

find_library(PANDA3D_LIBRARY NAMES panda PATH_SUFFIXES panda3d)
find_library(PANDA3D_P3FRAMEWORK_LIBRARY p3framework PATH_SUFFIXES panda3d)
find_library(PANDA3D_P3DTOOL_LIBRARY p3dtool PATH_SUFFIXES panda3d)
find_library(PANDA3D_P3DTOOLCONFIG_LIBRARY p3dtoolconfig PATH_SUFFIXES panda3d)
find_library(PANDA3D_PANDAEXPRESS_LIBRARY pandaexpress PATH_SUFFIXES panda3d)

include(FindPackageHandleStandardArgs)
find_package_handle_standard_args(Panda3D DEFAULT_MSG
    PANDA3D_INCLUDE_DIR
    PANDA3D_LIBRARY
    PANDA3D_P3FRAMEWORK_LIBRARY
    PANDA3D_P3DTOOL_LIBRARY
    PANDA3D_P3DTOOLCONFIG_LIBRARY
    PANDA3D_PANDAEXPRESS_LIBRARY)

set(PANDA3D_LIBRARIES
    ${PANDA3D_LIBRARY}
    ${PANDA3D_P3FRAMEWORK_LIBRARY}
    ${PANDA3D_P3DTOOL_LIBRARY}
    ${PANDA3D_P3DTOOLCONFIG_LIBRARY}
    ${PANDA3D_PANDAEXPRESS_LIBRARY})
set(PANDA3D_INCLUDE_DIRS ${PANDA3D_INCLUDE_DIR})
