= DAR - Data Archive File Format

DAR means "Data ARchive"

It's an archive format with optional per-file compression and with trailing file index.
File contents are simply concatenated (no padding is inserted).

All integer fields are big-endian.
All offsets are relative to start of the file (simple seek will always work).
Offsets are uint32, thus the total size limit is 4 GB.

Inspired by MAR (https://wiki.mozilla.org/Software_Update:MAR)

Features:

* The index at the end allows adding more files to the archive without shuffling
  content of other files. Only the index needs to be saved and written again at
  the end.
* When used without compression, the format allows mmapping the whole archive,
  searching for files in the index and reading them directly by the offset.
  No allocation required.
* The implementation is simple, no library needed (besides zlib for the optional compression).

----
    ARCHIVE:
    - HEADER - see below
    - FILE [NUMBER_OF_ENTRIES] - see below
    - INDEX - see below

    HEADER:
    - ID = "dar1" (4 bytes)
    - INDEX_OFFSET (4 bytes - uint32be) - offset to INDEX from start of file

    FILE:
    - CONTENT (CONTENT_SIZE bytes) - file data according to ENCODING
    - METADATA (METADATA_SIZE bytes) - file metadata - see File Metadata

    INDEX:
    - INDEX_SIZE (4 bytes - uint32be) - size of INDEX (including this field)
    - NUMBER_OF_ENTRIES (4 bytes - uint32be) - number of entries in index
    - INDEX_ENTRY [NUMBER_OF_ENTRIES] - see below

    INDEX_ENTRY:
    - CONTENT_OFFSET (4 bytes - uint32be) - offset to CONTENT from start of file
    - CONTENT_SIZE (4 bytes - uint32be) - size of CONTENT
    - METADATA_SIZE (4 bytes - uint32be) - size of METADATA
    - ENCODING (2 bytes - encoding ID) - see Encodings
    - NAME_SIZE (2 bytes - uint16be) - size of NAME
    - NAME (NAME_SIZE bytes) - file name
----

### Encodings

This is an extension point. The only required encoding is "raw plain data".

* "--" - raw plain data
* "zl" - deflate stream with zlib header (RFC-1950, RFC-1951),
         followed by PLAIN_SIZE (4 bytes uint32be, uncompressed file size module 2^32)

### File Metadata

This is an extension point. The format of the metadata is currently undefined.
METADATA_SIZE should always be 0. Unpacker may ignore the metadata.

The metadata block will contain the file permissions, xattrs etc.
It may also contain checksum(s).
