// Sample dictionary, mined from Wikipedia:
// https://en.wikipedia.org/wiki/Category:Star_Trek_terminology

static constexpr const char* g_dict[] = {
        "Alpha Quadrant",
        "Away team",
        "Bajoran Wormhole",
        "Baryon sweep",
        "Bell Riots",
        "Beta Quadrant",
        "Bilitrium",
        "Coaxial drive",
        "Stardate",
        "Delta Quadrant",
        "Dilithium",
        "Dunsel",
        "Gamma Quadrant",
        "General Order 12",
        "Grups",
        "Holaddiction",
        "Imzadi",
        "Jefferies tube",
        "Kobayashi Maru",
        "Kolvoord Starburst",
        "LCARS",
        "Linguacode",
        "M-5",
        "Neutral zone",
        "The Nexus",
        "Nitrium",
        "Omega particle",
        "Onlies",
        "Pa'nar Syndrome",
        "Pon farr",
        "Prime Directive",
        "Project Genesis",
        "Rules of Acquisition",
        "Sector",
        "Spatial anomaly",
        "Static warp bubble",
        "Subspace",
        "The Picard Maneuver",
        "Transporter psychosis",
        "Tranya",
        "Trellium-D",
        "Tri-Dimensional Chess",
        "Vermicula",
        "Vulcan nerve pinch",
        "Warp 10",
        "Xenopolycythemia",
        "Yeager Loop",
        "Zhian'tara",
};
